# Generated by Django 3.0.8 on 2020-07-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('prize', models.CharField(max_length=50, verbose_name='Награда')),
                ('poem', models.TextField(blank=True, verbose_name='Стих')),
                ('poem_choose', models.CharField(blank=True, max_length=6, verbose_name='Выбор стиха')),
                ('status', models.BooleanField(verbose_name='Статус выполнения')),
                ('activated', models.BooleanField(verbose_name='Активирован')),
                ('time_activate', models.DateTimeField(verbose_name='Время активации')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('image_add_one', models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение 1')),
                ('image_add_two', models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение 2')),
                ('image_add_three', models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение 3')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
    ]
